### ISSUE TITLE
SIGFPE when staking SplitCoinStakeOutput

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#1338]
GetNumberOfStakeOutputs returns 0.
```
(gdb) bt                                                                                                                                                                                 
#0  0xb685387c in raise () from /usr/lib/libpthread.so.0                                     
#1  0xb687a1f8 in __aeabi_ldiv0 () at /build/gcc/src/gcc/libgcc/config/arm/lib1funcs.S:1545
#2  0x004d464c in SplitCoinStakeOutput (blocknew=..., nReward=@0x4d464c: -2188643857705447424, fEnableStakeSplit=@0xafdfb208: false, fEnableSideStaking=@0xb6ffe900: false,
    vSideStakeAlloc=std::vector of length 0, capacity 0, nMinStakeSplitValue=@0xafdfb7a0: 80000000000, dEfficiency=@0xafdfb7a8: 0.90000000000000002) at miner.cpp:756
#3  0x004dc620 in StakeMiner (pwallet=0xafdfb8f8, pwallet@entry=0x12f8cc70) at miner.cpp:1406
#4  0x004ebd40 in ThreadStakeMiner (parg=0x12f8cc70) at net.cpp:1596      
#5  0xb6eeb4f0 in ?? () from /usr/lib/libboost_thread.so.1.68.0
#6  0xb68474e4 in start_thread () from /usr/lib/libpthread.so.0
#7  0xb67cba28 in ?? () from /usr/lib/libc.so.6
(gdb) frame 2
(gdb) p nSplitStakeOutputs
$1 = 0
(gdb) p nMaxOutputs                                                 
$2 = 2950674344                                                
(gdb) p nOutputsUsed                                           
$3 = 1                                         
(gdb) p nMinStakeSplitValue
$4 = (int64_t &) @0xafdfb7a0: 80000000000
(gdb) p dEfficiency
$5 = (double &) @0xafdfb7a8: 0.90000000000000002
(gdb) p nRemainingStakeOutputValue
$6 = 106786352532
(gdb) p GetNumberOfStakeOutputs(nRemainingStakeOutputValue, nMinStakeSplitValue, dEfficiency)
$7 = 0
```

**Comment by denravonska** [comment]
Should be fixed with #1340.
