### ISSUE TITLE
Tests segfault for 4.0.1.0 on openSUSE Leap 15.0 and Tumbleweed

### ISSUE THREAD

**Issue by theMarix** [gridcoin-community/Gridcoin-Research#1373]
I sadly currently lack the time to debug this further, but with 4.0.1.0 the `test_gridcoin` binary segfaults on my system for both, openSUSE Leap 15.0 and openSUSE Tumbleweed.

```
[  415s] + cd src
[  415s] + test/test_gridcoin
[  415s] unknown location(0): fatal error: in "Test setup": memory access violation at address: 0x00000040: no mapping at fault address
[  415s] Running 103 test cases...
```

**Comment by denravonska** [comment]
Unable to replicate this in Ubuntu 18.10. Looks like something boost does unless "Test setup" includes constructing our test context objects.

**Comment by jamescowens** [comment]
Was this off a repo or self-compiled?

**Comment by jamescowens** [comment]
I am updating my openSuSE tumbleweed to try and replicate this..

**Comment by jamescowens** [comment]
I just built using the brew path on the latest OpenSuSE tumbleweed with boost 1.68 and cannot reproduce. All 103 tests passed.

**Comment by theMarix** [comment]
Sorry for the long silence. I have been kept AFK by some things.

This is weird. This is when trying to create the package for the openSUSE repo, building of the 4.0.1.0 tag.

As this happens both, building for Leap and for Tumbleweed which use different versions of boost it seems unlikely to me that this is related to the boost version.

**Comment by theMarix** [comment]
So I just verified. Building straight from the repo, outside of the package build process, the issue does not occur. Thus, it seems to be related to some of the hardening flags automatically injected when building the binaries for a SUSE package.

**Comment by jamescowens** [comment]
Do you know what those flags are?

**Comment by theMarix** [comment]
So I tried rebuilding with the concrete flags and could not reproduce. Weirdly it now also works in the package build.

Sorry for the noise.

**Comment by theMarix** [comment]
One other thing I noted while debugging this: If building with `--with-gui=qt5` but not Qt5Test installed, configure will properly detect this and build with Gui but skip creation of the `test_gridcoin-qt` binary. IMHO opinion this is bad as `make check` will simply pass despite the missing test binary. `configure` should fail in this case unless `--disable-tests` or `--disable-gui-tests` is specified.

**Comment by smoe** [comment]
I can confirm the very same error for Debian Buster (testing). To reproduce:
 1. clone from current master
 2. have --with-incompatible-bdb added to configure (using db 5.3)
 3. make check

Boost has version 1.67

With a bit of bug hunting
```
moeller@big2:~/git/smoe/gridcoin-research-4.0.1.0/src/test$ ./test_gridcoin
unknown location(0): fatal error: in "Test setup": memory access violation at address: 0x00000040: no mapping at fault address
Running 103 test cases...

*** No errors detected
Test setup error:
```
and started from within gdb
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Boost.Test WARNING: token "test/test_gridcoin" does not correspond to the Boost.Test argument
                    and should be placed after all Boost.Test arguments and the -- separator.
                    For example: test_gridcoin --random -- test/test_gridcoin

Program received signal SIGSEGV, Segmentation fault.
0x0000555555645e73 in tinyformat::detail::FormatIterator::accept<int> (this=0x7fffffffb8d0, value=<error reading variable>) at ./tinyformat.h:584
584	void FormatIterator::accept(const T& value)
(gdb) bt
#0  0x0000555555645e73 in tinyformat::detail::FormatIterator::accept<int> (this=0x7fffffffb8d0, value=<error reading variable>) at ./tinyformat.h:584
#1  0x000055555570e41f in tinyformat::detail::format<int, int> (fmtIter=..., value1=<error reading variable>, args#0=@0x555555ade170: 0)
    at tinyformat.h:863
#2  0x00005555557c88f6 in tinyformat::detail::format<int, int, int> (value1=@0x555555ade170: 0, fmtIter=...) at tinyformat.h:863
#3  tinyformat::format<int, int, int> (v1=@0x555555ade170: 0, fmt=0x555555935062 "RA Starting %i %i %i \n", out=...) at tinyformat.h:903
#4  tinyformat::format<int, int, int> (v1=@0x555555ade170: 0, fmt=0x555555935062 "RA Starting %i %i %i \n") at tinyformat.h:910
#5  LogPrint<int, int, int> (category=0x0, format=0x555555935062 "RA Starting %i %i %i \n", v3=<optimized out>, v2=<optimized out>, v1=@0x555555ade170: 0)
    at util.h:137
#6  CTxDB::LoadBlockIndex (this=this@entry=0x7fffffffcc90) at txdb-leveldb.cpp:615
#7  0x00005555556fa6f0 in LoadBlockIndex (fAllowNew=true) at main.cpp:5111
#8  0x0000555555681bc1 in TestingSetup::TestingSetup (this=0x555555aa4610) at test/test_gridcoin.cpp:20
#9  boost::unit_test::ut_detail::global_configuration_impl<TestingSetup>::test_start (this=0x555555a06cc0 <gf_TestingSetup>)
    at /usr/include/boost/test/tree/global_fixture.hpp:75
#10 0x00007ffff7e5bf5e in boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke(boost::detail::function::function_buffer&)
    () from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#11 0x00007ffff7e5bb65 in boost::execution_monitor::catch_signals(boost::function<int ()> const&) ()
   from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#12 0x00007ffff7e5bc31 in boost::execution_monitor::execute(boost::function<int ()> const&) ()
   from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#13 0x00007ffff7e5bcfd in boost::execution_monitor::vexecute(boost::function<void ()> const&) ()
   from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#14 0x00007ffff7e838a9 in boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned int) ()
   from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#15 0x00007ffff7e609f1 in boost::unit_test::framework::run(unsigned long, bool) () from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#16 0x00007ffff7e81318 in boost::unit_test::unit_test_main(bool (*)(), int, char**) ()
   from /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so.1.67.0
#17 0x00007ffff73be09b in __libc_start_main (main=0x5555555d0be0 <main(int, char**)>, argc=2, argv=0x7fffffffe478, init=<optimized out>,
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe468) at ../csu/libc-start.c:308
#18 0x00005555555df44a in _start () at /usr/include/boost/test/tree/observer.hpp:40
```

**Comment by denravonska** [comment]
@smoe I think this is due to a print bug on an empty chain. It has been fixed in staging and in hotfix which hasn't been released yet. You can try this commit. https://github.com/gridcoin-community/Gridcoin-Research/commit/0623a900d25ca6feedb3cbd382e7f6949fedc164
The fix, if it solves your issue, will be included in the upcoming release, be it a hotfix or the Camilla release.

**Comment by smoe** [comment]
Checked out staging, from there checked into 0623a900d25ca6feedb3cbd382e7f6949fedc164, and it was very smooth, indeed. Error gone:
```
make  check-TESTS
make[4]: Entering directory '/home/moeller/git/smoe/gridcoin-research-4.0.1.0/src'
make[5]: Entering directory '/home/moeller/git/smoe/gridcoin-research-4.0.1.0/src'
PASS: test/test_gridcoin
============================================================================
Testsuite summary for Gridcoin 4.0.1
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[5]: Leaving directory '/home/moeller/git/smoe/gridcoin-research-4.0.1.0/src'
make[4]: Leaving directory '/home/moeller/git/smoe/gridcoin-research-4.0.1.0/src'
make[3]: Leaving directory '/home/moeller/git/smoe/gridcoin-research-4.0.1.0/src'
make[2]: Leaving directory '/home/moeller/git/smoe/gridcoin-research-4.0.1.0/src'
make[2]: Entering directory '/home/moeller/git/smoe/gridcoin-research-4.0.1.0'
make[2]: Nothing to be done for 'check-am'.
make[2]: Leaving directory '/home/moeller/git/smoe/gridcoin-research-4.0.1.0'
make[1]: Leaving directory '/home/moeller/git/smoe/gridcoin-research-4.0.1.0'
   create-stamp debian/debhelper-build-stamp
```
Many thanks for your quick reply!

**Comment by smoe** [comment]
Ping me if you want something uploaded to Debian.
