### ISSUE TITLE
View details of Vote transaction crash

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#785]
Segfault while trying to view details in gui of unconfirmed vote transaction crashes the wallet. 
Transaction containing text messages are not affected.
Other types of tx might be affected.
Does not crash after the tx was confirmed.
Gridcoin Qt v3.6.3.18-gce90fe349 ce90fe349ca30750358a26c864c4f2a8064d8a37 Linux
```
(gdb) continue
Executing method vote
Loaded staketime from index in 11,000000CPIDTime 1494866128,000000, GRCTime 1492274128,000000, WalletTime 1512753518,000000
CPIDAge 19116917,000000,StakeAge 21708917,000000,Poll Duration 2592000,000000
CommitTransaction:
CTransaction(hash=f4b5ad799d, nTime=1513983045, ver=1, vin.size=1, vout.size=2, nLockTime=0)
    CTxIn(COutPoint(f40a091a00, 1), scriptSig=3044022067574dca8d327363)
    CTxOut(nValue=0.99769, scriptPubKey=OP_DUP OP_HASH160 adaef2eba9a4b794cc07ca333ee866769df96376 OP_EQUALVERIFY OP_CHECKSIG)
    CTxOut(nValue=0.00001, scriptPubKey=OP_DUP OP_HASH160 314d56b06b86c82c2050d4b02d77216de474e0f0 OP_EQUALVERIFY OP_CHECKSIG)
keypool keep 7
WalletUpdateSpent found spent coin 83.37375145 gC f40a091a00958ff5a58063149d8b36f742c8a35d16fee86bd9f11c29e20bc233
NotifyTransactionChanged f40a091a00958ff5a58063149d8b36f742c8a35d16fee86bd9f11c29e20bc233 status=1
NotifyTransactionChanged f4b5ad799d5941340f40332b12ad556e7478f8d158e4f720c821afa8601fe44e status=0
NotifyTransactionChanged f40a091a00958ff5a58063149d8b36f742c8a35d16fee86bd9f11c29e20bc233 status=1
AcceptToMemoryPool : accepted f4b5ad799d5941340f40332b12ad556e7478f8d158e4f720c821afa8601fe44e (poolsz 1)
Response [{"Command":"vote"},{"Success":"Your CPID weight is 360 and your Balance weight is 265023. Your vote has been cast for topic casual:_boinc_blockchain_support_409904: With an Answer of Yes;Abstain: f4b5ad799d5941340f40332b12ad556e7478f8d158e4f720c821afa8601fe44e"}]
updateWallet f40a091a00958ff5a58063149d8b36f742c8a35d16fee86bd9f11c29e20bc233 1
   inWallet=1 inModel=1 Index=860-861 showTransaction=1 derivedStatus=1
updateWallet f4b5ad799d5941340f40332b12ad556e7478f8d158e4f720c821afa8601fe44e 0
   inWallet=1 inModel=0 Index=865-865 showTransaction=1 derivedStatus=0
updateWallet f40a091a00958ff5a58063149d8b36f742c8a35d16fee86bd9f11c29e20bc233 1
   inWallet=1 inModel=1 Index=860-861 showTransaction=1 derivedStatus=1
^C
(gdb) # NOTE: I double-clicked the transaction in tx list right after this resume
(gdb) continue

Thread 1 "gridcoinresearc" received signal SIGSEGV, Segmentation fault.
GetTxNormalBoincHashInfo[abi:cxx11](CMerkleTx const&) (mtx=...) at rpcrawtransaction.cpp:239
239                         int nEndHeight = pblockindex->nHeight - (BLOCKS_PER_DAY*14);
(gdb) p pblockindex 
$1 = (CBlockIndex *) 0x0
(gdb) bt
#0  0x00005555557c1c4d in GetTxNormalBoincHashInfo[abi:cxx11](CMerkleTx const&) (mtx=...)
    at rpcrawtransaction.cpp:239
#1  0x0000555555669d16 in TransactionDesc::toHTML(CWallet*, CWalletTx&) (wallet=<optimized out>, wtx=...)
    at qt/transactiondesc.cpp:311
#2  0x0000555555660cc6 in TransactionTablePriv::describe(TransactionRecord*) (rec=0x555556d04ad0, this=<optimized out>) at qt/transactiontablemodel.cpp:225
#3  0x0000555555660cc6 in TransactionTableModel::data(QModelIndex const&, int) const (this=<optimized out>, index=..., role=<optimized out>) at qt/transactiontablemodel.cpp:616
#4  0x00007ffff5312a49 in QSortFilterProxyModel::data(QModelIndex const&, int) const ()
    at /usr/lib/libQt5Core.so.5
#5  0x000055555565e103 in QModelIndex::data(int) const (arole=258, this=0x555556e0cfb0)
    at /usr/include/qt/QtCore/qabstractitemmodel.h:432
#6  0x000055555565e103 in TransactionDescDialog::TransactionDescDialog(QModelIndex const&, QWidget*) (this=0x7fffffffc3e0, idx=..., parent=<optimized out>) at qt/transactiondescdialog.cpp:18
#7  0x0000555555622d6e in TransactionView::showDetails() (this=<optimized out>) at qt/transactionview.cpp:388
#8  0x00007ffff5381c16 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#9  0x0000555555642e82 in TransactionView::doubleClicked(QModelIndex const&) (this=<optimized out>, _t1=...)
    at qt/moc_transactionview.cpp:195
#10 0x00007ffff5381c16 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#11 0x00007ffff654d0e6 in QAbstractItemView::doubleClicked(QModelIndex const&) () at /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff65596be in QAbstractItemView::mouseDoubleClickEvent(QMouseEvent*) () at /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff633a347 in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff63dd5ef in QFrame::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#15 0x00007ffff6559354 in QAbstractItemView::viewportEvent(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff5351d2c in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) ()
    at /usr/lib/libQt5Core.so.5
#17 0x00007ffff62f9f08 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#18 0x00007ffff6301f81 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#19 0x00007ffff5352060 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#20 0x00007ffff6300f0a in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () at /usr/lib/libQt5Widgets.so.5
#21 0x00007ffff6354d81 in  () at /usr/lib/libQt5Widgets.so.5
#22 0x00007ffff63574c1 in  () at /usr/lib/libQt5Widgets.so.5
#23 0x00007ffff62f9f2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#24 0x00007ffff6301a06 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#25 0x00007ffff5352060 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#26 0x00007ffff5b3b572 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
    at /usr/lib/libQt5Gui.so.5
#27 0x00007ffff5b3cf36 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/libQt5Gui.so.5
#28 0x00007ffff5b1448c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Gui.so.5
---Type <return> to continue, or q <return> to quit---
#29 0x00007fffec4e24b1 in  () at /usr/lib/libQt5XcbQpa.so.5
#30 0x00007ffff0a4f270 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#31 0x00007ffff0a50f69 in  () at /usr/lib/libglib-2.0.so.0
#32 0x00007ffff0a50fae in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#33 0x00007ffff53accd1 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#34 0x00007ffff535048b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#35 0x00007ffff53594d8 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#36 0x00005555555a931d in main(int, char**) (argc=<optimized out>, argv=0x7fffffffe018) at qt/bitcoin.cpp:337
(gdb)
```

**Comment by denravonska** [comment]
Fixed by @tomasbrod.
