### ISSUE TITLE
Crash +gdb

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#875]
```
*** Error in `/home/tomas/prj/gridcoinresearch.pkg/src/gridcoinresearch/src/gridcoinresearchd': double free or corruption (!prev): 0x00007fffc0038a20 ***
[Switching to Thread 0x7fffd2fc6700 (LWP 32164)]

Thread 9 "grc-msghand" hit Breakpoint 1, 0x00007ffff5508d00 in abort () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff5508d00 in abort () from /usr/lib/libc.so.6
#1  0x00007ffff554a437 in __libc_message () from /usr/lib/libc.so.6
#2  0x00007ffff5550d34 in malloc_printerr () from /usr/lib/libc.so.6
#3  0x00007ffff5552439 in _int_free () from /usr/lib/libc.so.6
#4  0x000055555564a913 in __gnu_cxx::new_allocator<char>::deallocate (this=0x7fffd2fc55e0, __p=<optimized out>)
    at /usr/include/c++/7.2.1/ext/new_allocator.h:125
#5  std::allocator_traits<std::allocator<char> >::deallocate (__a=..., __n=<optimized out>, __p=<optimized out>)
    at /usr/include/c++/7.2.1/bits/alloc_traits.h:462
#6  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_destroy (
    __size=<optimized out>, this=0x7fffd2fc55e0) at /usr/include/c++/7.2.1/bits/basic_string.h:226
#7  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose (
    this=0x7fffd2fc55e0) at /usr/include/c++/7.2.1/bits/basic_string.h:221
#8  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string (
    this=0x7fffd2fc55e0, __in_chrg=<optimized out>) at /usr/include/c++/7.2.1/bits/basic_string.h:647
#9  CNode::PushVersion (this=this@entry=0x7fffd400da50) at net.cpp:740
#10 0x0000555555621dab in ProcessMessage (pfrom=pfrom@entry=0x7fffd400da50, strCommand="aries", vRecv=..., 
    nTimeReceived=<optimized out>) at main.cpp:6302
#11 0x00005555556267c4 in ProcessMessages (pfrom=0x7fffd400da50) at main.cpp:7140
#12 0x0000555555646f51 in ThreadMessageHandler2 (parg=parg@entry=0x0) at net.cpp:2056
#13 0x000055555564713c in ThreadMessageHandler (parg=0x0) at net.cpp:2014
#14 0x00007ffff752044f in ?? () from /usr/lib/libboost_thread.so.1.65.1
#15 0x00007ffff617c08a in start_thread () from /usr/lib/libpthread.so.0
#16 0x00007ffff55c942f in clone () from /usr/lib/libc.so.6
(gdb) list net.cpp:740
735
736         std::string sboinchashargs = DefaultBoincHashArgs();
737         uint256 boincHashRandNonce = GetRandHash();
738         std::string nonce = boincHashRandNonce.GetHex();
739         std::string pw1 = RetrieveMd5(nonce+","+sboinchashargs);
740         std::string mycpid = GlobalCPUMiningCPID.cpidv2;
741         std::string acid = GetCommandNonce("aries");
742         std::string sGRCAddress = DefaultWalletAddress();
743
744         PushMessage("aries", PROTOCOL_VERSION, nonce, pw1,
(gdb) 
```

**Comment by iFoggz** [comment]
that the aries caused crash related to overflow u fix in ur pr?

**Comment by denravonska** [comment]
Was this in prod with 3.7.5.0?

**Comment by tomasbrod** [comment]
This is a master version of 8a6432e5a48303ae90bd17b4bcb58cf838dbe711, built with qmake.
This error occurs while SENDING packet (as a reply to something). The aries crash brought up by @barton2526 was while processing a aries/acid.
Error occurred at line accessing GlobalCPUMiningCPID for the sake of including it in the protocol message.
Yes, this code was deleted in my PR, but the crash occurred before I wrote the PR.

**Comment by tomasbrod** [comment]
#871 #890
