### ISSUE TITLE
LevelDB error and crash on startup +gdb

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Research#900]
Suddenly:
```
LevelDB batch commit failure: Corruption: bad entry in block                                                      
ERROR: AcceptBlock() : AddToBlockIndex failed
```
no more blocks were accepted. neither locally generated.
And after restart:
```
Time to memorize diskindex containing 466640 blocks :            4115ms
gridcoinresearchd: kernel.cpp:736: unsigned int GetStakeModifierChecksum(const CBlockIndex*): Assertion `pindex->pprev || pindex->GetBlockHash() == (!fTestNet ? hashGenesisBlock : hashGenesisBlockTestNet)' failed.

Thread 1 "gridcoinresearc" hit Breakpoint 1, 0x00007ffff559ad00 in abort () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff559ad00 in abort () from /usr/lib/libc.so.6
#1  0x00007ffff55920bc in __assert_fail_base () from /usr/lib/libc.so.6
#2  0x00007ffff5592133 in __assert_fail () from /usr/lib/libc.so.6
#3  0x000055555577aadf in GetStakeModifierChecksum (pindex=pindex@entry=0x5555580d5450) at kernel.cpp:736
#4  0x00005555557177e9 in CTxDB::LoadBlockIndex (this=this@entry=0x7fffffffcc20) at txdb-leveldb.cpp:433
#5  0x00005555556258ba in LoadBlockIndex (fAllowNew=fAllowNew@entry=true) at main.cpp:4770
#6  0x00005555555d025c in AppInit2 (threads=...) at init.cpp:711
#7  0x0000555555585f7b in AppInit (argc=11, argv=0x7fffffffdf28) at gridcoinresearchd.cpp:91
#8  0x000055555557c93a in main (argc=11, argv=0x7fffffffdf28) at gridcoinresearchd.cpp:127
(gdb) list kernel.cpp:736
731     }
732
733     // Get stake modifier checksum
734     unsigned int GetStakeModifierChecksum(const CBlockIndex* pindex)
735     {
736         assert (pindex->pprev || pindex->GetBlockHash() == (!fTestNet ? hashGenesisBlock : hashGenesisBlockTestNet));
737         // Hash previous checksum with flags, hashProofOfStake and nStakeModifier
738         CDataStream ss(SER_GETHASH, 0);
739         if (pindex->pprev)
740             ss << pindex->pprev->nStakeModifierChecksum;
(gdb) 
```

**Comment by tomasbrod** [comment]
There was presumably a system wide memory corruption. Unrelated.
